version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth
    restart: always
    container_name: keycloak_container
    depends_on:
      - backend
    networks:
      - auth-network

  backend:
    container_name: backend_container
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - auth-network
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      - keycloak
      - backend
    networks:
      - auth-network

networks:
  auth-network: